language: php

php:
  - 7

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-source install

before_script:
 - chmod +x ./tests/setup.sh

script:
  - ./vendor/bin/phpunit --colors
